/** Resposta CMS para `sections_visibility` (singleton). `id` null = ainda sem linha no banco (valores virtuais todos true). */
export interface SectionsVisibilityCmsType {
  id: string | null;
  subscriptionEnabledAtracaoLocal: boolean;
  subscriptionEnabledGastronomia: boolean;
  subscriptionEnabledMuseu: boolean;
  subscriptionEnabledFazendaHistorica: boolean;
  subscriptionEnabledHospedagem: boolean;
  subscriptionEnabledAgenteCultural: boolean;
  subscriptionEnabledTrilha: boolean;
  subscriptionEnabledEvento: boolean;
  subscriptionEnabledSobre: boolean;
  subscriptionEnabledNossaHistoria: boolean;
  subscriptionEnabledComoChegar: boolean;
  subscriptionEnabledMapaInterativo: boolean;
  subscriptionEnabledMapaTempoReal: boolean;
  subscriptionEnabledRoteiro: boolean;
  subscriptionEnabledCircuitoTuristico: boolean;
  tenantVisibleAtracaoLocal: boolean;
  tenantVisibleGastronomia: boolean;
  tenantVisibleMuseu: boolean;
  tenantVisibleFazendaHistorica: boolean;
  tenantVisibleHospedagem: boolean;
  tenantVisibleAgenteCultural: boolean;
  tenantVisibleTrilha: boolean;
  tenantVisibleEvento: boolean;
  tenantVisibleSobre: boolean;
  tenantVisibleNossaHistoria: boolean;
  tenantVisibleComoChegar: boolean;
  tenantVisibleMapaInterativo: boolean;
  tenantVisibleMapaTempoReal: boolean;
  tenantVisibleRoteiro: boolean;
  tenantVisibleCircuitoTuristico: boolean;
  roteiroIaIncludeGastronomia: boolean;
  cmsMenuVisibleAtracaoLocal: boolean;
  cmsMenuVisibleEvento: boolean;
  cmsMenuVisibleGastronomia: boolean;
  cmsMenuVisibleHospedagem: boolean;
  cmsMenuVisibleTrilha: boolean;
  cmsMenuVisibleAgenteCultural: boolean;
  cmsMenuVisibleCircuitoTuristico: boolean;
  cmsMenuVisibleNossaHistoria: boolean;
  subscriptionUpdatedById: string | null;
  subscriptionUpdatedAt: string | null;
  tenantVisibleUpdatedById: string | null;
  tenantVisibleUpdatedAt: string | null;
  cmsMenuUpdatedById: string | null;
  cmsMenuUpdatedAt: string | null;
  createdAt: string | null;
  updatedAt: string | null;
}
